# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Delta3DWeightsC <- function(vx, Datasample) {
    .Call(`_DatabionicSwarm_Delta3DWeightsC`, vx, Datasample)
}

DijkstraSSSP <- function(Adj, Costs, source) {
    .Call(`_DatabionicSwarm_DijkstraSSSP`, Adj, Costs, source)
}

PswarmRadiusParallel <- function(DataBotsPos, DataDists, AllallowedDBPosR0, IndPossibleDBPosRe, IndPossibleDBPosIm, Lines, Columns, Radius, NumAllDB, NumChoDB, NumFreeShape1, NumJumps, Origin1, Origin2, Happiness, MinIterations, HappinessInclination, Eps, debug) {
    .Call(`_DatabionicSwarm_PswarmRadiusParallel`, DataBotsPos, DataDists, AllallowedDBPosR0, IndPossibleDBPosRe, IndPossibleDBPosIm, Lines, Columns, Radius, NumAllDB, NumChoDB, NumFreeShape1, NumJumps, Origin1, Origin2, Happiness, MinIterations, HappinessInclination, Eps, debug)
}

PswarmRadiusSequential <- function(AllDataBotsPosOld, Radius, DataDists, IndPossibleDBPosR, RadiusPositionsschablone, pp, Nullpunkt, Lines, Columns, nBots, limit, steigungsverlaufind, Happiness, debug) {
    .Call(`_DatabionicSwarm_PswarmRadiusSequential`, AllDataBotsPosOld, Radius, DataDists, IndPossibleDBPosR, RadiusPositionsschablone, pp, Nullpunkt, Lines, Columns, nBots, limit, steigungsverlaufind, Happiness, debug)
}

findPossiblePositionsCsingle <- function(RadiusPositionsschablone, jumplength, alpha, Lines) {
    .Call(`_DatabionicSwarm_findPossiblePositionsCsingle`, RadiusPositionsschablone, jumplength, alpha, Lines)
}

rDistanceToroidCsingle <- function(AllDataBotsPosX, AllDataBotsPosY, AllallowedDBPosR0, Lines, Columns, Nullpunkt) {
    .Call(`_DatabionicSwarm_rDistanceToroidCsingle`, AllDataBotsPosX, AllDataBotsPosY, AllallowedDBPosR0, Lines, Columns, Nullpunkt)
}

rcppPar_DistanceToroid <- function(AllDataBotsPosX, AllDataBotsPosY, AllallowedDBPosR0, Lines, Columns, Nullpunkt) {
    .Call(`_DatabionicSwarm_rcppPar_DistanceToroid`, AllDataBotsPosX, AllDataBotsPosY, AllallowedDBPosR0, Lines, Columns, Nullpunkt)
}

sampleC <- function(x, len) {
    .Call(`_DatabionicSwarm_sampleC`, x, len)
}

trainstepC <- function(vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid, NoCases) {
    .Call(`_DatabionicSwarm_trainstepC`, vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid, NoCases)
}

trainstepC2 <- function(esomwts, aux, DataSampled, BMUsampled, Lines, Columns, Weights, Radius, toroid, NoCases) {
    .Call(`_DatabionicSwarm_trainstepC2`, esomwts, aux, DataSampled, BMUsampled, Lines, Columns, Weights, Radius, toroid, NoCases)
}

